SET SERVEROUTPUT ON;
SET VERIFY OFF;

CREATE OR REPLACE VIEW RECEIPT (TOKEN_NUM, ORDERED_ITEMS, UNITS, PRICES, NAME, ADDRESS) AS SELECT O.O_ID, O.O_ITEMS, O.QUANTITY, O.PRICE, O.CUSTOMER_NAME, O.CUSTOMER_ADDRESS FROM ORDERS O;



DECLARE

	O1 ORDERS.O_ITEMS%TYPE;
	O2 ORDERS.PRICE%TYPE;
	O3 ORDERS.QUANTITY%TYPE;

BEGIN

	SELECT ORDERED_ITEMS,UNITS,PRICES INTO O1,O2,O3 FROM RECEIPT;


END;
/